#############################################################################
# Makefile for building: SDLOpenGL
# Generated by qmake (3.0) (Qt 5.1.0) on: Wed Apr 2 12:14:26 2014
# Project:  SDLOpenGL.pro
# Template: app
# Command: /opt/qtsdk/5.1.0/gcc_64/bin/qmake -spec linux-clang CONFIG+=debug CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile SDLOpenGL.pro
#############################################################################

MAKEFILE      = Makefile

first: debug
install: debug-install
uninstall: debug-uninstall
QMAKE         = /opt/qtsdk/5.1.0/gcc_64/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = $(COPY_DIR)
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
SUBTARGETS    =  \
		debug \
		release


debug: FORCE
	$(MAKE) -f $(MAKEFILE).Debug
debug-make_first: FORCE
	$(MAKE) -f $(MAKEFILE).Debug 
debug-all: FORCE
	$(MAKE) -f $(MAKEFILE).Debug all
debug-clean: FORCE
	$(MAKE) -f $(MAKEFILE).Debug clean
debug-distclean: FORCE
	$(MAKE) -f $(MAKEFILE).Debug distclean
debug-install: FORCE
	$(MAKE) -f $(MAKEFILE).Debug install
debug-uninstall: FORCE
	$(MAKE) -f $(MAKEFILE).Debug uninstall
release: FORCE
	$(MAKE) -f $(MAKEFILE).Release
release-make_first: FORCE
	$(MAKE) -f $(MAKEFILE).Release 
release-all: FORCE
	$(MAKE) -f $(MAKEFILE).Release all
release-clean: FORCE
	$(MAKE) -f $(MAKEFILE).Release clean
release-distclean: FORCE
	$(MAKE) -f $(MAKEFILE).Release distclean
release-install: FORCE
	$(MAKE) -f $(MAKEFILE).Release install
release-uninstall: FORCE
	$(MAKE) -f $(MAKEFILE).Release uninstall

Makefile: SDLOpenGL.pro .qmake.cache /opt/qtsdk/5.1.0/gcc_64/mkspecs/linux-clang/qmake.conf /opt/qtsdk/5.1.0/gcc_64/mkspecs/features/spec_pre.prf \
		/opt/qtsdk/5.1.0/gcc_64/mkspecs/common/shell-unix.conf \
		/opt/qtsdk/5.1.0/gcc_64/mkspecs/common/unix.conf \
		/opt/qtsdk/5.1.0/gcc_64/mkspecs/common/linux.conf \
		/opt/qtsdk/5.1.0/gcc_64/mkspecs/common/gcc-base.conf \
		/opt/qtsdk/5.1.0/gcc_64/mkspecs/common/gcc-base-unix.conf \
		/opt/qtsdk/5.1.0/gcc_64/mkspecs/common/clang.conf \
		/opt/qtsdk/5.1.0/gcc_64/mkspecs/qconfig.pri \
		/opt/qtsdk/5.1.0/gcc_64/mkspecs/modules/qt_lib_bootstrap.pri \
		/opt/qtsdk/5.1.0/gcc_64/mkspecs/modules/qt_lib_clucene.pri \
		/opt/qtsdk/5.1.0/gcc_64/mkspecs/modules/qt_lib_concurrent.pri \
		/opt/qtsdk/5.1.0/gcc_64/mkspecs/modules/qt_lib_core.pri \
		/opt/qtsdk/5.1.0/gcc_64/mkspecs/modules/qt_lib_dbus.pri \
		/opt/qtsdk/5.1.0/gcc_64/mkspecs/modules/qt_lib_declarative.pri \
		/opt/qtsdk/5.1.0/gcc_64/mkspecs/modules/qt_lib_designer.pri \
		/opt/qtsdk/5.1.0/gcc_64/mkspecs/modules/qt_lib_designercomponents.pri \
		/opt/qtsdk/5.1.0/gcc_64/mkspecs/modules/qt_lib_gui.pri \
		/opt/qtsdk/5.1.0/gcc_64/mkspecs/modules/qt_lib_help.pri \
		/opt/qtsdk/5.1.0/gcc_64/mkspecs/modules/qt_lib_multimedia.pri \
		/opt/qtsdk/5.1.0/gcc_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/opt/qtsdk/5.1.0/gcc_64/mkspecs/modules/qt_lib_network.pri \
		/opt/qtsdk/5.1.0/gcc_64/mkspecs/modules/qt_lib_opengl.pri \
		/opt/qtsdk/5.1.0/gcc_64/mkspecs/modules/qt_lib_openglextensions.pri \
		/opt/qtsdk/5.1.0/gcc_64/mkspecs/modules/qt_lib_platformsupport.pri \
		/opt/qtsdk/5.1.0/gcc_64/mkspecs/modules/qt_lib_printsupport.pri \
		/opt/qtsdk/5.1.0/gcc_64/mkspecs/modules/qt_lib_qml.pri \
		/opt/qtsdk/5.1.0/gcc_64/mkspecs/modules/qt_lib_qmldevtools.pri \
		/opt/qtsdk/5.1.0/gcc_64/mkspecs/modules/qt_lib_qmltest.pri \
		/opt/qtsdk/5.1.0/gcc_64/mkspecs/modules/qt_lib_qtmultimediaquicktools.pri \
		/opt/qtsdk/5.1.0/gcc_64/mkspecs/modules/qt_lib_quick.pri \
		/opt/qtsdk/5.1.0/gcc_64/mkspecs/modules/qt_lib_quickparticles.pri \
		/opt/qtsdk/5.1.0/gcc_64/mkspecs/modules/qt_lib_script.pri \
		/opt/qtsdk/5.1.0/gcc_64/mkspecs/modules/qt_lib_scripttools.pri \
		/opt/qtsdk/5.1.0/gcc_64/mkspecs/modules/qt_lib_sensors.pri \
		/opt/qtsdk/5.1.0/gcc_64/mkspecs/modules/qt_lib_serialport.pri \
		/opt/qtsdk/5.1.0/gcc_64/mkspecs/modules/qt_lib_sql.pri \
		/opt/qtsdk/5.1.0/gcc_64/mkspecs/modules/qt_lib_svg.pri \
		/opt/qtsdk/5.1.0/gcc_64/mkspecs/modules/qt_lib_testlib.pri \
		/opt/qtsdk/5.1.0/gcc_64/mkspecs/modules/qt_lib_uitools.pri \
		/opt/qtsdk/5.1.0/gcc_64/mkspecs/modules/qt_lib_v8.pri \
		/opt/qtsdk/5.1.0/gcc_64/mkspecs/modules/qt_lib_webkit.pri \
		/opt/qtsdk/5.1.0/gcc_64/mkspecs/modules/qt_lib_webkitwidgets.pri \
		/opt/qtsdk/5.1.0/gcc_64/mkspecs/modules/qt_lib_widgets.pri \
		/opt/qtsdk/5.1.0/gcc_64/mkspecs/modules/qt_lib_x11extras.pri \
		/opt/qtsdk/5.1.0/gcc_64/mkspecs/modules/qt_lib_xml.pri \
		/opt/qtsdk/5.1.0/gcc_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/opt/qtsdk/5.1.0/gcc_64/mkspecs/features/qt_functions.prf \
		/opt/qtsdk/5.1.0/gcc_64/mkspecs/features/qt_config.prf \
		/opt/qtsdk/5.1.0/gcc_64/mkspecs/linux-clang/qmake.conf \
		/opt/qtsdk/5.1.0/gcc_64/mkspecs/features/spec_post.prf \
		.qmake.cache \
		/opt/qtsdk/5.1.0/gcc_64/mkspecs/features/exclusive_builds.prf \
		/opt/qtsdk/5.1.0/gcc_64/mkspecs/features/default_pre.prf \
		/opt/qtsdk/5.1.0/gcc_64/mkspecs/features/unix/default_pre.prf \
		/opt/qtsdk/5.1.0/gcc_64/mkspecs/features/resolve_config.prf \
		/opt/qtsdk/5.1.0/gcc_64/mkspecs/features/default_post.prf \
		/opt/qtsdk/5.1.0/gcc_64/mkspecs/features/qml_debug.prf \
		/opt/qtsdk/5.1.0/gcc_64/mkspecs/features/declarative_debug.prf \
		/opt/qtsdk/5.1.0/gcc_64/mkspecs/features/warn_on.prf \
		/opt/qtsdk/5.1.0/gcc_64/mkspecs/features/qt.prf \
		/opt/qtsdk/5.1.0/gcc_64/mkspecs/features/resources.prf \
		/opt/qtsdk/5.1.0/gcc_64/mkspecs/features/moc.prf \
		/opt/qtsdk/5.1.0/gcc_64/mkspecs/features/unix/opengl.prf \
		/opt/qtsdk/5.1.0/gcc_64/mkspecs/features/uic.prf \
		/opt/qtsdk/5.1.0/gcc_64/mkspecs/features/unix/thread.prf \
		/opt/qtsdk/5.1.0/gcc_64/mkspecs/features/wayland-scanner.prf \
		/opt/qtsdk/5.1.0/gcc_64/mkspecs/features/testcase_targets.prf \
		/opt/qtsdk/5.1.0/gcc_64/mkspecs/features/exceptions.prf \
		/opt/qtsdk/5.1.0/gcc_64/mkspecs/features/yacc.prf \
		/opt/qtsdk/5.1.0/gcc_64/mkspecs/features/lex.prf \
		SDLOpenGL.pro \
		/opt/qtsdk/5.1.0/gcc_64/lib/libQt5OpenGL.prl \
		/opt/qtsdk/5.1.0/gcc_64/lib/libQt5Widgets.prl \
		/opt/qtsdk/5.1.0/gcc_64/lib/libQt5Gui.prl \
		/opt/qtsdk/5.1.0/gcc_64/lib/libQt5Core.prl
	$(QMAKE) -spec linux-clang CONFIG+=debug CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile SDLOpenGL.pro
/opt/qtsdk/5.1.0/gcc_64/mkspecs/features/spec_pre.prf:
/opt/qtsdk/5.1.0/gcc_64/mkspecs/common/shell-unix.conf:
/opt/qtsdk/5.1.0/gcc_64/mkspecs/common/unix.conf:
/opt/qtsdk/5.1.0/gcc_64/mkspecs/common/linux.conf:
/opt/qtsdk/5.1.0/gcc_64/mkspecs/common/gcc-base.conf:
/opt/qtsdk/5.1.0/gcc_64/mkspecs/common/gcc-base-unix.conf:
/opt/qtsdk/5.1.0/gcc_64/mkspecs/common/clang.conf:
/opt/qtsdk/5.1.0/gcc_64/mkspecs/qconfig.pri:
/opt/qtsdk/5.1.0/gcc_64/mkspecs/modules/qt_lib_bootstrap.pri:
/opt/qtsdk/5.1.0/gcc_64/mkspecs/modules/qt_lib_clucene.pri:
/opt/qtsdk/5.1.0/gcc_64/mkspecs/modules/qt_lib_concurrent.pri:
/opt/qtsdk/5.1.0/gcc_64/mkspecs/modules/qt_lib_core.pri:
/opt/qtsdk/5.1.0/gcc_64/mkspecs/modules/qt_lib_dbus.pri:
/opt/qtsdk/5.1.0/gcc_64/mkspecs/modules/qt_lib_declarative.pri:
/opt/qtsdk/5.1.0/gcc_64/mkspecs/modules/qt_lib_designer.pri:
/opt/qtsdk/5.1.0/gcc_64/mkspecs/modules/qt_lib_designercomponents.pri:
/opt/qtsdk/5.1.0/gcc_64/mkspecs/modules/qt_lib_gui.pri:
/opt/qtsdk/5.1.0/gcc_64/mkspecs/modules/qt_lib_help.pri:
/opt/qtsdk/5.1.0/gcc_64/mkspecs/modules/qt_lib_multimedia.pri:
/opt/qtsdk/5.1.0/gcc_64/mkspecs/modules/qt_lib_multimediawidgets.pri:
/opt/qtsdk/5.1.0/gcc_64/mkspecs/modules/qt_lib_network.pri:
/opt/qtsdk/5.1.0/gcc_64/mkspecs/modules/qt_lib_opengl.pri:
/opt/qtsdk/5.1.0/gcc_64/mkspecs/modules/qt_lib_openglextensions.pri:
/opt/qtsdk/5.1.0/gcc_64/mkspecs/modules/qt_lib_platformsupport.pri:
/opt/qtsdk/5.1.0/gcc_64/mkspecs/modules/qt_lib_printsupport.pri:
/opt/qtsdk/5.1.0/gcc_64/mkspecs/modules/qt_lib_qml.pri:
/opt/qtsdk/5.1.0/gcc_64/mkspecs/modules/qt_lib_qmldevtools.pri:
/opt/qtsdk/5.1.0/gcc_64/mkspecs/modules/qt_lib_qmltest.pri:
/opt/qtsdk/5.1.0/gcc_64/mkspecs/modules/qt_lib_qtmultimediaquicktools.pri:
/opt/qtsdk/5.1.0/gcc_64/mkspecs/modules/qt_lib_quick.pri:
/opt/qtsdk/5.1.0/gcc_64/mkspecs/modules/qt_lib_quickparticles.pri:
/opt/qtsdk/5.1.0/gcc_64/mkspecs/modules/qt_lib_script.pri:
/opt/qtsdk/5.1.0/gcc_64/mkspecs/modules/qt_lib_scripttools.pri:
/opt/qtsdk/5.1.0/gcc_64/mkspecs/modules/qt_lib_sensors.pri:
/opt/qtsdk/5.1.0/gcc_64/mkspecs/modules/qt_lib_serialport.pri:
/opt/qtsdk/5.1.0/gcc_64/mkspecs/modules/qt_lib_sql.pri:
/opt/qtsdk/5.1.0/gcc_64/mkspecs/modules/qt_lib_svg.pri:
/opt/qtsdk/5.1.0/gcc_64/mkspecs/modules/qt_lib_testlib.pri:
/opt/qtsdk/5.1.0/gcc_64/mkspecs/modules/qt_lib_uitools.pri:
/opt/qtsdk/5.1.0/gcc_64/mkspecs/modules/qt_lib_v8.pri:
/opt/qtsdk/5.1.0/gcc_64/mkspecs/modules/qt_lib_webkit.pri:
/opt/qtsdk/5.1.0/gcc_64/mkspecs/modules/qt_lib_webkitwidgets.pri:
/opt/qtsdk/5.1.0/gcc_64/mkspecs/modules/qt_lib_widgets.pri:
/opt/qtsdk/5.1.0/gcc_64/mkspecs/modules/qt_lib_x11extras.pri:
/opt/qtsdk/5.1.0/gcc_64/mkspecs/modules/qt_lib_xml.pri:
/opt/qtsdk/5.1.0/gcc_64/mkspecs/modules/qt_lib_xmlpatterns.pri:
/opt/qtsdk/5.1.0/gcc_64/mkspecs/features/qt_functions.prf:
/opt/qtsdk/5.1.0/gcc_64/mkspecs/features/qt_config.prf:
/opt/qtsdk/5.1.0/gcc_64/mkspecs/linux-clang/qmake.conf:
/opt/qtsdk/5.1.0/gcc_64/mkspecs/features/spec_post.prf:
.qmake.cache:
/opt/qtsdk/5.1.0/gcc_64/mkspecs/features/exclusive_builds.prf:
/opt/qtsdk/5.1.0/gcc_64/mkspecs/features/default_pre.prf:
/opt/qtsdk/5.1.0/gcc_64/mkspecs/features/unix/default_pre.prf:
/opt/qtsdk/5.1.0/gcc_64/mkspecs/features/resolve_config.prf:
/opt/qtsdk/5.1.0/gcc_64/mkspecs/features/default_post.prf:
/opt/qtsdk/5.1.0/gcc_64/mkspecs/features/qml_debug.prf:
/opt/qtsdk/5.1.0/gcc_64/mkspecs/features/declarative_debug.prf:
/opt/qtsdk/5.1.0/gcc_64/mkspecs/features/warn_on.prf:
/opt/qtsdk/5.1.0/gcc_64/mkspecs/features/qt.prf:
/opt/qtsdk/5.1.0/gcc_64/mkspecs/features/resources.prf:
/opt/qtsdk/5.1.0/gcc_64/mkspecs/features/moc.prf:
/opt/qtsdk/5.1.0/gcc_64/mkspecs/features/unix/opengl.prf:
/opt/qtsdk/5.1.0/gcc_64/mkspecs/features/uic.prf:
/opt/qtsdk/5.1.0/gcc_64/mkspecs/features/unix/thread.prf:
/opt/qtsdk/5.1.0/gcc_64/mkspecs/features/wayland-scanner.prf:
/opt/qtsdk/5.1.0/gcc_64/mkspecs/features/testcase_targets.prf:
/opt/qtsdk/5.1.0/gcc_64/mkspecs/features/exceptions.prf:
/opt/qtsdk/5.1.0/gcc_64/mkspecs/features/yacc.prf:
/opt/qtsdk/5.1.0/gcc_64/mkspecs/features/lex.prf:
SDLOpenGL.pro:
/opt/qtsdk/5.1.0/gcc_64/lib/libQt5OpenGL.prl:
/opt/qtsdk/5.1.0/gcc_64/lib/libQt5Widgets.prl:
/opt/qtsdk/5.1.0/gcc_64/lib/libQt5Gui.prl:
/opt/qtsdk/5.1.0/gcc_64/lib/libQt5Core.prl:
qmake: FORCE
	@$(QMAKE) -spec linux-clang CONFIG+=debug CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile SDLOpenGL.pro

qmake_all: FORCE

make_first: debug-make_first release-make_first FORCE
all: debug-all release-all FORCE
clean: debug-clean release-clean FORCE
distclean: debug-distclean release-distclean FORCE
	-$(DEL_FILE) Makefile

debug-mocclean:
	$(MAKE) -f $(MAKEFILE).Debug mocclean
release-mocclean:
	$(MAKE) -f $(MAKEFILE).Release mocclean
mocclean: debug-mocclean release-mocclean

debug-mocables:
	$(MAKE) -f $(MAKEFILE).Debug mocables
release-mocables:
	$(MAKE) -f $(MAKEFILE).Release mocables
mocables: debug-mocables release-mocables

check: first
FORCE:

$(MAKEFILE).Debug: Makefile
$(MAKEFILE).Release: Makefile
